function interfata2(tab_str,M1)
   fig1=figure('Name','Proiect TELEFONIE');
        set(fig1,'Numbertitle','off');
        set(fig1,'Color',[0.8 0.8 0.8]);
        set(fig1,'Units','normalized');
        set(fig1,'Position',[0 0.55 0.6 0.3]);
        set(fig1,'Tag','fereastra1');
    uicontrol('Style', 'text',...
                    'Units', 'normalized',...
                    'BackgroundColor','white',...
                    'ForegroundColor','black',...
                    'Position',[0.25 0.85 0.4 0.1],...
                    'String', 'Structura multicadru E1',...
                    'Fontsize', 17,...
                    'FontWeight','demi',...
                    'HorizontalAlignment','center');
     uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'BackgroundColor','cyan',...
                'ForegroundColor','black',...
                'Position',[0.25 0.75 0.4 0.07],...
                'String', 'Slotul de timp 0',...
                'Fontsize', 8,...
                'FontWeight','demi',...
                'HorizontalAlignment','center');
   uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'Position',[0.25 0.65 0.2 0.1],...
                'String','Sincronizarea in cadre pare',...
                'Callback','close;interfata2(tab_str,M1);tabel2(tab_str)');
   uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'Position',[0.45 0.65 0.2 0.1],...
                'String','Calculare CRC',...
                'Callback','close;interfata3(M1);tabel(tab_str)');
   uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'Position',[0.25 0.55 0.2 0.1],...
                'String','Sincronizarea in cadre impare',...
                'Callback','close;interfata2(tab_str,M1);tabel3(tab_str)');
end
