function interfata1(tab_str,M1)
   fig1=figure('Name','Proiect TELEFONIE');
        set(fig1,'Numbertitle','off');
        set(fig1,'Color',[0.8 0.8 0.8]);
        set(fig1,'Units','normalized');
        set(fig1,'Position',[0.3 0.45 0.6 0.45]);
       uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'BackgroundColor','white',...
                'ForegroundColor','black',...
                'Position',[0.25 0.85 0.4 0.1],...
                'String', 'Structura multicadru E1',...
                'Fontsize', 17,...
                'FontWeight','demi',...
                'HorizontalAlignment','center');
    uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.4 0.7 0.15 0.1],...
            'String','Generare multicadru',...
            'Callback','close;interfata2(tab_str,M1);tabel(tab_str)');
end
