function interfata3(M1)
     fig1=figure('Name','Proiect TELEFONIE');
        set(fig1,'Numbertitle','off');
        set(fig1,'Color',[0.8 0.8 0.8]);
        set(fig1,'Units','normalized');
        set(fig1,'Position',[0 0.45 0.6 0.45]);
        set(fig1,'Tag','fereastra1');
       uicontrol('Style', 'text',...
                    'Units', 'normalized',...
                    'BackgroundColor','cyan',...
                    'ForegroundColor','black',...
                    'Position',[0.25 0.75 0.4 0.2],...
                    'String', 'Cyclic Redundancy Ceck 4 (CRC-4)',...
                    'Fontsize', 17,...
                    'FontWeight','demi',...
                    'HorizontalAlignment','center');
     uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'BackgroundColor',[0.8 0.8 0.8],...
                'ForegroundColor','black',...
                'Position',[0.25 0.65 0.4 0.07],...
                'String', 'Polinomul generator X^4+X+1',...
                'Fontsize', 8,...
                'FontWeight','demi',...
                'HorizontalAlignment','center');
   uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'Position',[0.25 0.55 0.2 0.1],...
                'String','Inserare biti CRC',...
                'Callback','close;start_CRC(M1)');
   uicontrol('Style','pushbutton',...
                'Units','normalized',...
                'Position',[0.45 0.55 0.2 0.1],...
                'String','Eronare+Recalculare+Biti de eroare',...
                'Callback','close;eronare_recalculare(M1)');
end